//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDUCCIONES_EMPLEADOS
    {
        public int idDeduccionEmpleado { get; set; }
        public int idEmpleado { get; set; }
        public int idDeduccion { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fechaPago { get; set; }
    
        public virtual TIPO_DEDUCCIONES TIPO_DEDUCCIONES { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
