//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.DEDUCCIONES_EMPLEADOS = new HashSet<DEDUCCIONES_EMPLEADOS>();
            this.PAGO_EMPLEADOS = new HashSet<PAGO_EMPLEADOS>();
        }
    
        public int idEmpleado { get; set; }
        public int idPersona { get; set; }
        public int departamento { get; set; }
        public int puesto { get; set; }
        public decimal salarioMensual { get; set; }
        public int portacionArma { get; set; }
        public Nullable<System.DateTime> vencimientoPermisoArma { get; set; }
        public string numeroCuentaBancaria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDUCCIONES_EMPLEADOS> DEDUCCIONES_EMPLEADOS { get; set; }
        public virtual PARAMETROS PARAMETROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO_EMPLEADOS> PAGO_EMPLEADOS { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual PARAMETROS PARAMETROS1 { get; set; }
        public virtual PARAMETROS PARAMETROS2 { get; set; }
    }
}
