//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_EMPLEADOS
    {
        public int idPago { get; set; }
        public int idEmpleado { get; set; }
        public decimal salarioBruto { get; set; }
        public decimal totalDeducciones { get; set; }
        public decimal salarioNeto { get; set; }
        public System.DateTime fechaPago { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
