//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int idPersona { get; set; }
        public string numeroIdentificacion { get; set; }
        public string nombrePersona { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public int genero { get; set; }
        public int estado { get; set; }
        public int nacionalidad { get; set; }
        public string correoElectronico { get; set; }
        public string telefono { get; set; }
        public string direccionResidencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual PARAMETROS PARAMETROS { get; set; }
        public virtual PARAMETROS PARAMETROS1 { get; set; }
        public virtual PARAMETROS PARAMETROS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
