//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int idUsuario { get; set; }
        public int idPersona { get; set; }
        public int idRol { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public Nullable<decimal> intentos_usuario { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
